### ISSUE TITLE
N550JK problem

### ISSUE THREAD

**Issue by alirezatheh** [qiqco/Asus-N550JV-i5-4200H#1]
CPU i7 4710HQ
Intel HD 4600
can't boot with OC EFI.
any suggestion?

**Comment by qiqco** [comment]
What's the status of clover?
I've determined the reason for OpenCore

**Comment by AlirezaH320** [comment]
both raise same error. it seems its something related to SMSBatteryManager.kext. with the message:
"battery 0 has no remained capacity reported."

**Comment by AlirezaH320** [comment]
both raise same error. it seems its something related to SMCBatteryManager.kext. with the message:
"battery 0 has no remained capacity reported."

**Comment by alirezatheh** [comment]
both raise same error. it seems it is something related to SMCBatteryManager.kext. error message:
"battery 0 has no remained capacity reported."

**Comment by qiqco** [comment]
How do you understand OpenCore?
You can try it in config.plist Try to cancel the following content
ACPI:Deselect SSDT-Batt.aml
     
Deselect Renaming of batt

Kext:Deselect SMCBatteryManager.kext

**Comment by qiqco** [comment]
> “电池0没有剩余

I think it's the ACPI error caused by the difference between my motherboard and yours

**Comment by alirezatheh** [comment]
I already had a working EFI without battery. I need yours for battery configurations. I also saw your [video](https://www.bilibili.com/video/BV11y4y167w7) on bilibili.com. in that video it seems you have the same motherboard as mine. can I have the EFI of it?
![image](https://user-images.githubusercontent.com/17493246/107855845-1be3bb00-6e3a-11eb-9dd0-ddaf7e503ee3.png)

**Comment by qiqco** [comment]
Of course, you said you need a battery patch, and I will help you find it. Just in these days, can you share your EFI? I want to share it with those who can't use my EFI later

**Comment by qiqco** [comment]
I've been out recently. Maybe you'll have to wait a few days

**Comment by alirezatheh** [comment]
> Of course, you said you need a battery patch, and I will help you find it. Just in these days, can you share your EFI? I want to share it with those who can't use my EFI later

Of course, but I am still working on it. when it completed I will share.

**Comment by alirezatheh** [comment]
> I've been out recently. Maybe you'll have to wait a few days

It will be awesome if I can have the EFI that belongs to the image that I shared whenever you can.

**Comment by qiqco** [comment]
[N550JV bat.zip](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5977718/N550JV.bat.zip)
Try and tell me if it works

**Comment by alirezatheh** [comment]
Battery is ok now. [Here](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5981062/EFI.zip) is my EFI. there is some other issues that you can help me now.
1 - Touchscreen is not working.
2 - Ar9485 Bluetooth is on but doesn't detect any device.
3 - Current VRAM is 1536 MB, I want 2048 MB

**Comment by alirezatheh** [comment]
> ![image](https://user-images.githubusercontent.com/17493246/107855845-1be3bb00-6e3a-11eb-9dd0-ddaf7e503ee3.png)

Do you have the EFI that belongs to this?

**Comment by qiqco** [comment]
Is your touchpad Elan's PS2
In GitHub is my OpenCore

**Comment by alirezatheh** [comment]
touchpad is ok. touchscreen is not. in your GitHub your CPU i5 but here is i7 🤔

**Comment by qiqco** [comment]
OpenCore can change the CPU display model

**Comment by qiqco** [comment]
Touch screen I don't know, I don't have it

**Comment by qiqco** [comment]
Modify VRAM to 2048MB
[config.plist.zip](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5981449/config.plist.zip)

**Comment by qiqco** [comment]
[AR9485 Bluetooth.zip](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5981442/AR9485.Bluetooth.zip)

**Comment by alirezatheh** [comment]
> Modify VRAM to 2048MB
> [config.plist.zip](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5981449/config.plist.zip)

worked.

**Comment by alirezatheh** [comment]
> AR9485 Bluetooth.zip

not working.

**Comment by qiqco** [comment]
> > AR9485 Bluetooth.zip
> 
> 不工作。

I am not very clear about this, my AR9485 does not have Bluetooth, and now I have changed to BCM43224

**Comment by alirezatheh** [comment]
ok thank you for your time.🙏

**Comment by qiqco** [comment]
I may submit your EFI to GitHub. Do you agree? I will indicate the source

**Comment by alirezatheh** [comment]
Yes. if it would help someone why not.

**Comment by qiqco** [comment]
thank you

**Comment by AlirezaH320** [comment]
do you have slow boot time too?

**Comment by qiqco** [comment]
I need 5 to 10 seconds, I don't think it's very slow

**Comment by alirezatheh** [comment]
I fixed Bluetooth and touchscreen. now I disabled verbose and stuck at fixing boot resolution. any idea?
[Here](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5987638/config.plist.zip) is my new config.plist.

**Comment by qiqco** [comment]
Thank you for your contribution

**Comment by alirezatheh** [comment]
> I fixed Bluetooth and touchscreen. now I disabled verbose and stuck at fixing boot resolution. any idea?
> [Here](https://github.com/qiqco/Asus-N550JV-i5-4200H/files/5987638/config.plist.zip) is my new config.plist.

I disabled CSM, when CSM disabled boot resolution is fine but after that Mac display is showing a lot of glitches and noises. so I enabled it again. any idea?

**Comment by alirezatheh** [comment]
Update: I managed to fix boot resolution by modding my BIOS. Just replaced CsmVideo with HermitCsmVideo and everything is great now.

**Comment by alirezatheh** [comment]
Does your ComboJack microphone works?

**Comment by qiqco** [comment]
Yes

**Comment by alirezatheh** [comment]
I have made a [repo](https://github.com/AlirezaH320/asus-n550jk-hackintosh) for this. I hope it helps someone.😅

**Comment by qiqco** [comment]
Can I put your EFI on my GitHub project
